<a href="https://colab.research.google.com/github/dxqianwei/qianwei/blob/master/tst1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b = np.pad(a,((0,0),(1,1),(0,0)),"constant",constant_values=(0,11))
print(np.max(a,axis=1, keepdims=True))

In [0]:
import tensorflow as tf
from keras import backend as K


Using TensorFlow backend.


In [0]:
w1 = tf.Variable(tf.Variable(tf.random_normal([4, 3], mean=1, stddev=4, seed = 1)))
 
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(w1)
    print(sess.run(w1))

<tf.Variable 'Variable_13:0' shape=(4, 3) dtype=float32_ref>
[[-2.2452729   6.938395    1.2613175 ]
 [-8.770817    1.3969936   3.3648973 ]
 [ 3.3712919  -7.4917183  -1.8915889 ]
 [ 0.7749185   3.5741792  -0.05729628]]


In [0]:
import tensorflow as tf
from keras import backend as K

w1 = tf.Variable(tf.Variable(tf.random_normal([4, 3, 5], mean=1, stddev=4, seed = 1)))
index_max = K.argmax(w1, axis = -1) 
val_max = K.max(w1, axis = -1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(w1))
    print(index_max.eval())
    print(val_max.eval())

[[[-2.2452729   6.938395    1.2613175  -8.770817    1.3969936 ]
  [ 3.3648973   3.3712919  -7.4917183  -1.8915889   0.7749185 ]
  [ 3.5741792  -0.05729628  8.426533    3.2713668  -0.5313436 ]]

 [[-4.9413733   6.0470843   0.8987757  -0.05851877  7.131255  ]
  [-5.9719086  -0.75157166 -1.26404     2.282677    5.531324  ]
  [-8.113029    2.9312482  -4.250835    2.4274013  -5.9211335 ]]

 [[ 0.83932906  4.598648   -4.5223565   6.925849    0.01802081]
  [-1.9305887   0.21641421  1.286832    3.5319235  -5.284763  ]
  [ 6.317525   -3.693468    1.1261784   2.9082098   2.747768  ]]

 [[-0.26723564 -0.8030013  -6.2242627   1.4995985  -2.0826168 ]
  [-1.9849663  -0.1278131  -6.835262   -0.35044277  5.1207933 ]
  [ 7.053607    1.9006323  -0.14264834  2.0753016   7.984844  ]]]
[[1 1 2]
 [4 4 1]
 [3 3 0]
 [3 4 4]]
[[6.938395  3.3712919 8.426533 ]
 [7.131255  5.531324  2.9312482]
 [6.925849  3.5319235 6.317525 ]
 [1.4995985 5.1207933 7.984844 ]]


In [0]:
X= "nihao Ha"
sentence_words = [w.lower() for w in X.split()]
print(sentence_words)

['nihao', 'ha']


In [0]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation,Reshape
from keras.layers import concatenate
from keras.utils import plot_model
from keras.layers import Input, Lambda
from keras.models import Model

def slice(x,index):
  return x[:,:,index]

a = Input(shape=(4,2))
x1 = Lambda(slice,output_shape=(4,1),arguments={'index':0})(a)
x2 = Lambda(slice,output_shape=(4,1),arguments={'index':1})(a)
x1 = Reshape((4,1,1))(x1)
x2 = Reshape((4,1,1))(x2)
output = concatenate([x1,x2])

model = Model(a, output)
x_test = np.array([[[1,2],[2,3],[3,4],[4,5]]])
model.predict(x_test)
plot_model(model, to_file='lambda.png',show_shapes=True)
#下载到本地电脑
#from google.colab import files
#files.download('lambda.png')
#下载到Gdrive
from google.colab import drive
drive.mount('/content/gdrive')
#连接Gdrive
#from google.colab import drive
#drive.mount('/content/drive/')

Mounted at /content/gdrive


In [0]:
!pip show keras

In [0]:
!pip show graphviz

In [0]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD
from keras.utils import np_utils    
from keras.utils import plot_model


def run():
    # 构建神经网络
    model = Sequential()
    model.add(Dense(4, input_dim=2, kernel_initializer='uniform'))
    model.add(Activation('relu'))
    model.add(Dense(2, kernel_initializer='uniform'))
    model.add(Activation('sigmoid'))
    sgd = SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])

    # 神经网络可视化
    plot_model(model, to_file='model.png')
    from google.colab import drive
    drive.mount('/content/gdrive/', force_remount=True)
  
if __name__ == '__main__':
    run()

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [0]:
!ls
!echo "Hello World"

gdrive	sample_data
Hello World


In [0]:
import tensorflow as tf
x1 = tf.constant(1.0, shape=[1,3,3,1])
x2 = tf.constant(1.0, shape=[1,6,6,3])

kernel = tf.constant(1.0, shape=[3,3,3,1])       #[filter_height, filter_width, in_channels, out_channels]
x3 = tf.constant(1.0, shape=[1,8,9,3])           #[batch, in_height, in_width, in_channels]
y2 = tf.nn.conv2d(x3, kernel, strides=[1,3,3,1], padding="SAME")

with tf.Session() as sess:
  print(y2.eval())
  print(y2.shape)

[[[[27.]
   [27.]
   [27.]]

  [[27.]
   [27.]
   [27.]]

  [[18.]
   [18.]
   [18.]]]]
(1, 3, 3, 1)


In [0]:
import tensorflow as tf
tf.set_random_seed(1)
a_C = tf.random_normal([1, 4, 4, 3], mean=1, stddev=4)
with tf.Session() as test:
  a_C = test.run(a_C)
  print(type(a_C))
  C_shape = tf.reshape(a_C, shape=(16,3))
  print(type(C_shape))
  print(test.run(tf.square(2)))

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>
4


In [0]:
import numpy as np
tst = np.array([1,2,3])
print(tst.shape)
print(tst.shape[0])
tst2 = tst.reshape(tst.shape[0], 1)
print(tst2.shape)
print(tst2[0])

(3,)
3
(3, 1)
[1]


In [0]:
import numpy as np
og = np.ogrid[:3, :3]
print(og)
print(og.shape)

In [0]:
import numpy as np
def bilinear_kernel(in_channels, out_channels, kernel_size):
    factor = (kernel_size + 1) // 2
    if kernel_size % 2 == 1:
        center = factor - 1
    else:
        center = factor - 0.5
    og = np.ogrid[:kernel_size, :kernel_size]
    filt = (1 - abs(og[0] - center) / factor) * \
           (1 - abs(og[1] - center) / factor)
    weight = np.zeros((in_channels, out_channels, kernel_size, kernel_size),
                      dtype='float32')
    weight[range(in_channels), range(out_channels), :, :] = filt
    return nd.array(weight)
